### PR TITLE
Feat/issue 17509007

### PR DESCRIPTION
**Pull request by cbanupama**
added node_modules to .gitignore and UI set up done in angular

### CODE REVIEW

**Comment by jagadeshanh** [comment]
@cbanupama please remove node_modules under my-api

**Comment by jagadeshanh** [comment]
Also keep the folder structure as
-> api -> nodejs code
-> ui ->angular code

**Comment by cbanupama** [comment]
> Also keep the folder structure as -> api -> nodejs code -> ui ->angular code

@jagadeshanh 
nodejs or nodejs code
angular or angular code

**Comment by cbanupama** [comment]
> > Also keep the folder structure as -> api -> nodejs code -> ui ->angular code
> 
> @jagadeshanh nodejs or nodejs code angular or angular code

I added as a api->nodejs-code and ui->angular-code

**Pull request closed without merging**
